# === INPAINTOR PARAMETERS ===

# FIRST_PILLAR
START_OF_FIRST_PILLAR: 150
END_OF_FIRST_PILLAR: 205

# SECOND_PILLAR
START_OF_SECOND_PILLAR: 445
END_OF_SECOND_PILLAR: 490

# THIRD_PILLAR
START_OF_THIRD_PILLAR: 790
END_OF_THIRD_PILLAR: 845

# FOURTH_PILLAR
START_OF_FOURTH_PILLAR: 1085
END_OF_FOURTH_PILLAR: 1120