# === INPAINTOR PARAMETERS ===

# FIRST_PILLAR
START_OF_FIRST_PILLAR: 170
END_OF_FIRST_PILLAR: 205

# SECOND_PILLAR
START_OF_SECOND_PILLAR: 440
END_OF_SECOND_PILLAR: 490

# THIRD_PILLAR
START_OF_THIRD_PILLAR: 805
END_OF_THIRD_PILLAR: 840

# FOURTH_PILLAR
START_OF_FOURTH_PILLAR: 1080
END_OF_FOURTH_PILLAR: 1125