# === INPAINTOR PARAMETERS ===

# FIRST_PILLAR
START_OF_FIRST_PILLAR: 170
END_OF_FIRST_PILLAR: 215

# SECOND_PILLAR
START_OF_SECOND_PILLAR: 420
END_OF_SECOND_PILLAR: 490

# THIRD_PILLAR
START_OF_THIRD_PILLAR: 800
END_OF_THIRD_PILLAR: 855

# FOURTH_PILLAR
START_OF_FOURTH_PILLAR: 1080
END_OF_FOURTH_PILLAR: 1140