# === INPAINTOR PARAMETERS ===

# FIRST_PILLAR
START_OF_FIRST_PILLAR: 145
END_OF_FIRST_PILLAR: 185

# SECOND_PILLAR
START_OF_SECOND_PILLAR: 400
END_OF_SECOND_PILLAR: 475

# THIRD_PILLAR
START_OF_THIRD_PILLAR: 785
END_OF_THIRD_PILLAR: 840

# FOURTH_PILLAR
START_OF_FOURTH_PILLAR: 1045
END_OF_FOURTH_PILLAR: 1120