# === INPAINTOR PARAMETERS ===

# FIRST_PILLAR
START_OF_FIRST_PILLAR: 145
END_OF_FIRST_PILLAR: 215

# SECOND_PILLAR
START_OF_SECOND_PILLAR: 420
END_OF_SECOND_PILLAR: 490

# THIRD_PILLAR
START_OF_THIRD_PILLAR: 795
END_OF_THIRD_PILLAR: 830

# FOURTH_PILLAR
START_OF_FOURTH_PILLAR: 1060
END_OF_FOURTH_PILLAR: 1120