# === INPAINTOR PARAMETERS ===

# FIRST_PILLAR
START_OF_FIRST_PILLAR: 150
END_OF_FIRST_PILLAR: 210

# SECOND_PILLAR
START_OF_SECOND_PILLAR: 420
END_OF_SECOND_PILLAR: 490

# THIRD_PILLAR
START_OF_THIRD_PILLAR: 800
END_OF_THIRD_PILLAR: 840

# FOURTH_PILLAR
START_OF_FOURTH_PILLAR: 1060
END_OF_FOURTH_PILLAR: 1120